### ISSUE TITLE
[RP-OH] <OriTech>

### ISSUE THREAD

**Issue by BloodRain121** [StoryAnvil/ResourcesAndIssues#16]
### Link to requested mod

https://www.curseforge.com/minecraft/mc-mods/oritech

### Any other info?

...

### Little checking

- [X] I checked [issues](https://github.com/StoryAnvil/ResourcesAndIssues/issues) for duplicates

**Comment by denisJaved** [comment]
Added [oritech](https://storyanvil.github.io/page?wiki=projects/oreHighlighter#:~:text=Mod%20name-,0.10.3,-Oritech) in [`V1.0.1`](https://www.curseforge.com/minecraft/texture-packs/universal-ore-highlighter/files/5896368)
